---
title: "Test_Display_Graph"
author: "Maxime THOOR"
date: "08/04/2020"
output: html_document
---

```{r}
library(ggplot2)
```


```{r}
data=read.csv("https://opendata.lillemetropole.fr/explore/dataset/indice-qualite-de-lair/download/?format=csv&timezone=Europe/Berlin&use_labels_for_header=true", head=TRUE, sep=";")
keeps = c("date_ech", "valeur")
data = data[keeps]
names(data)[names(data)=="date_ech"] <- "date"
data$date <- as.Date(data$date, "%Y-%m-%d")
```

```{r}
head(data)
```


## Display all predictions made

```{r}
require("jsonlite")
require("httr")
```

```{r}
df_prediction<-read.csv("df_prediction.csv", header = TRUE, sep = ",")

df_prediction$value = as.numeric(as.character(df_prediction$value))
df_prediction$dateofprediction = as.Date(df_prediction$dateofprediction, format = "%Y-%m-%d")
names(df_prediction)[names(df_prediction)=="dateofprediction"] <- "date"
names(df_prediction)[names(df_prediction)=="value"] <- "predictValue"
head(df_prediction)
```

Concatenate both datasets iq and prediction
```{r}
library(dplyr)
concat_df = left_join(df_prediction, data, by="date")
```


```{r}
listOfdf = split(concat_df, concat_df$typeofprediction)
head(listOfdf)
```

```{r}
library(ggplot2)
count = 0
for(JPlusX in listOfdf){
  count=count+1
}
```
